### ISSUE TITLE
Error running docker_clean_vfs.py 

### ISSUE THREAD

**Issue by wesleymusgrove** [darthbinamira/dotfiles#1]
I'm getting the following error trying to run this script to clean up my docker vfs directory:

```
$ python ~/docker_clean_vfs.py 
Traceback (most recent call last):
  File "~/docker_clean_vfs.py", line 55, in <module>
    sys.exit(main())
  File "~/docker_clean_vfs.py", line 34, in main
    volumes = client.inspect_container(container['Id'])['Volumes']
KeyError: 'Volumes'
```

Any ideas why this is happening?

**Comment by darthbinamira** [comment]
not sure why. can you give some details like

os/distro
python ver

it seems it is failing trying to get the volumes from containers

**Comment by darthbinamira** [comment]
also forgot to ask which docker ver u have. pls include that

**Comment by wesleymusgrove** [comment]
Ubuntu 14.04
Python 2.7.6
Docker version 1.9.1, build a34a1d5

I've got two volumes that I think are duplicates and are taking up several gigs.  I need to keep one because it's a volume that belongs to a container that I use daily.  The other volume can be deleted.  I just don't know which volume belongs to which container.  There's also a bunch of other volumes that I don't know what they're for or why they're still hanging around taking up space, which is why I'm trying to clean them up.

Specifically the two volumes that are taking up several gigs are located at:

```
/var/lib/docker/vfs/dir/dbbdc5bc68cb587639750ed6c1e18a107db7b55edbd355ac66fd41ec785efc1c
/var/lib/docker/vfs/dir/0a588e04d212fd716de216cda4d7d69ef695c3534673720ab239e894ce1ed9b1
```

Trying to analyze those volumes doesn't work:

```
$ docker volume inspect dbbdc5bc68cb587639750ed6c1e18a107db7b55edbd355ac66fd41ec785efc1c
Error response from daemon: no such volume

$ docker volume inspect 0a588e04d212fd716de216cda4d7d69ef695c3534673720ab239e894ce1ed9b1
Error response from daemon: no such volume
```

Is there anything else I can do to figure out which containers or images those volumes are linked to?

**Comment by darthbinamira** [comment]
It seems Docker 1.10 has changed the location of volumes because I don't have /var/lib/docker/vfs, instead I have /var/lib/docker/volumes.

What you can do is

```
$ docker inspect <container_id>
```

And check for the "Volumes"  (or "Mount" in Docker 1.10) field. You'll have to do it on all the containers you have either running or already exited, to check which of them uses the above 2 volumes you mentioned.

As far as the script goes, I haven't used it that often.. got it from here - https://github.com/docker/docker/issues/6354
The issue is still open, but there are others who have also commented with their solution.

**Comment by darthbinamira** [comment]
@wesleymusgrove you might want to check this out: https://hub.docker.com/r/martin/docker-cleanup-volumes/

I am going to remove the contents of the script and redirect anyone to other tools since this is outdated and I don't plan to use it myself.
