### ISSUE TITLE
KeyError: Volumes

### ISSUE THREAD

**Issue by millelog** [darthbinamira/dotfiles#2]
This might just be due to updates to the docker-py api but the client.inspect_container() doesn't seem to return a dictionary that has a 'Volumes' key anymore?

[root@jupyter docker_python]# ./docker_clean.py 
Traceback (most recent call last):
  File "./docker_clean.py", line 53, in <module>
    sys.exit(main())
  File "./docker_clean.py", line 32, in main
    volumes = client.inspect_container(container['Id'])['Volumes']
KeyError: 'Volumes'

Any info or help would be cool, I'm just trying to find something to maintain all of the volumes I'm having to mount and remove as I test different things as they're starting to conflict sometimes.

**Comment by darthbinamira** [comment]
hey @millelog - I haven't maintained this for over a year now, you might be better off using other scripts that are updated. First issue opened was the same as this :) https://github.com/darthbinamira/dotfiles/issues/1
